# Generated by Django 4.0.6 on 2022-12-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineMS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
