# Generated by Django 4.0.6 on 2022-12-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ticket_no',
            field=models.CharField(max_length=100),
        ),
    ]
