# Generated by Django 4.0.6 on 2022-12-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineMS', '0002_reservation_gender_alter_reservation_ticket_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightschedule',
            name='arr_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='dept_time',
            field=models.DateTimeField(),
        ),
    ]
