# Generated by Django 4.0.6 on 2022-12-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineMS', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
