# Generated by Django 4.0.6 on 2022-12-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineMS', '0004_remove_reservation_user_reservation_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='id',
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='flight_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
