# Generated by Django 4.0.6 on 2022-12-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineMS', '0005_remove_route_id_alter_flightschedule_flight_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='no_of_tickets',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=100),
        ),
    ]
