# Generated by Django 4.0.6 on 2022-12-16 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AirlineMS', '0005_airlines_airplanes_airport_flights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Confirmed'), ('2', 'Cancelled')], max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirlineMS.flights')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AirlineMS.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
