# Generated by Django 4.0.6 on 2022-12-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineMS', '0006_reservation_no_of_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='no_of_tickets',
            new_name='number_of_tickets',
        ),
    ]
