# Generated by Django 4.0.6 on 2022-12-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineMS', '0007_rename_no_of_tickets_reservation_number_of_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
