# Generated by Django 4.0.6 on 2022-12-23 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineMS', '0009_alter_route_flying_from_alter_route_flying_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='airplane',
        ),
        migrations.AddField(
            model_name='airplanes',
            name='airlines',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AirlineMS.airlines'),
        ),
    ]
