# Generated by Django 4.0.6 on 2022-12-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineMS', '0010_remove_airport_airplane_airplanes_airlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='flying_from',
            field=models.CharField(choices=[('DHK', 'DHK'), ('CTG', 'CTG'), ('CXB', 'CXB'), ('JSR', 'JSR'), ('SDP', 'SDP'), ('BZL', 'BZL'), ('SYL', 'SYL')], default='DHK', max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='flying_to',
            field=models.CharField(choices=[('DHK', 'DHK'), ('CTG', 'CTG'), ('CXB', 'CXB'), ('JSR', 'JSR'), ('SDP', 'SDP'), ('BZL', 'BZL'), ('SYL', 'SYL')], default='CTG', max_length=100),
        ),
    ]
