# Generated by Django 4.0.6 on 2022-12-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineMS', '0011_alter_route_flying_from_alter_route_flying_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
