# Generated by Django 4.0.6 on 2022-12-23 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineMS', '0012_delete_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AirlineMS.route'),
        ),
    ]
