# Generated by Django 4.0.6 on 2022-12-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineMS', '0013_reservation_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='flight',
        ),
    ]
