# Generated by Django 4.0.6 on 2022-12-24 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineMS', '0015_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='total_tickets',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='flightschedule',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='flightschedule', serialize=False, to='AirlineMS.flights'),
        ),
    ]
